#PBS -N water_QMMM
#PBS -q gemini-cpu
#PBS -e job.$PBS_JOBID
#PBS -l nodes=1:ppn=8
#PBS -l walltime=7:00:00:00

cd $PBS_O_WORKDIR

#change to your conda
# conda_env=gcc75

# here we need to use the conda download and environment for newer psi4
# default PACE installation is too old for DMA

module load anaconda3
source activate ~/data/.conda/envs/gcc75_exp 

export PATH=~/data/experimental/psi4/psi4/bin/bin:$PATH
export PYTHONPATH=~/data/experimental/psi4/psi4/bin/lib:$PYTHONPATH

export myscratch=~/scratch/psi4.$PBS_JOBID
export PSI_SCRATCH=$myscratch
mkdir -p $PSI_SCRATCH

# export PSIDATADIR=""
# export PSIDATADIR=~/data/.conda/envs/gcc/share/psi4/   

export OMP_NUM_THREADS=8
export MKL_NUM_THREADS=8
export OPENMM_CPU_THREADS=8

python run_test.py

rm -r $PSI_SCRATCH

