#PBS -N water_QMMM
#PBS -q gemini-cpu
#PBS -o job.$PBS_JOBID
#PBS -e job.$PBS_JOBID
#PBS -l nodes=1:ppn=1
#PBS -l walltime=1:00:00:00

cd $PBS_O_WORKDIR

conda_env=gcc72

module load intel/19.0
module load anaconda3

source activate $conda_env


export myscratch=~/scratch/psi4.$PBS_JOBID
export PSI_SCRATCH=$myscratch
mkdir -p $PSI_SCRATCH

export PSIDATADIR=""
export PSIDATADIR=~/.conda/envs/${conda_env}/share/psi4/   

python run_QM_MM.py >& water_QMMM.out
rm -r $PSI_SCRATCH

